blog/urls.py
from django.urls import path

from .views import base_blog, blog_list, blog_detail


urlpatterns = [
    path('', base_blog, name='base_blog_url'),
    path('blogs/', blog_list, name='blog_list_url'),
    path('<str:slug>/', blog_detail, name='blog_detail_url'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import base_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base_view, name='base_url'),
    path('blog/', include('blog.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, username, email, date_of_birth, gender, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
            gender=gender,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, date_of_birth, gender, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username,
            email,
            password=password,
            date_of_birth=date_of_birth,
            gender=gender,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    CHOICES = [
        ('M', 'Man'),
        ('W', 'Woman'),
    ]
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    gender = models.CharField(max_length=300, choices = CHOICES)
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'date_of_birth', 'gender']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

blog/models.py
from django.db import models


class Blog(models.Model):
    CHOICES = [
        ('VG', 'Videogames'),
        ('F', 'Films'),
        ('P', 'Politics'),
        ('T', 'Travel'),
    ]
    title = models.CharField(max_length=150)
    description = models.TextField()
    blog_topic = models.CharField(max_length=300, choices = CHOICES)
    slug = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return self.title

class Category(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=150, unique=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Comment(models.Model):
    body = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.create_time

class Tag(models.Model):
    title = models.CharField(max_length=150)
    frequency = models.IntegerField()
    slug = models.SlugField(max_length=150, unique=True)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

from .models import Blog, Post


def base_blog(request):
    #blog = Blog.objects.get(slug__iexact=slug)
    return render(request, 'blog/base_blog.html')

def blog_list(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/blog_list.html', context={'blogs': blogs})

def blog_detail(request, slug):
    blog = Blog.objects.get(slug__iexact=slug)
    posts = Post.objects.filter(blog=blog)
    ordered_posts = posts.order_by('-create_time')[:3]
    return render(request, 'blog/blog_detail.html', context={'blog': blog, 'posts': ordered_posts})

django_blog/views.py
from django.shortcuts import render


def base_view(request):
    return render(request, 'base.html')

blog/templates/blog/base_blog.html
{% extends 'base.html' %}

{% block title %}
    Blog
{% endblock %}

{% block content %}
   <h1>Blog</h1>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block title %}
    Blog {{ blog.title }}
{% endblock %}

{% block content %}
    <div class="container mt-4 col-6">
        <div class="detail-base text-center">
            <h1>{{ blog.title }}</h1>
              <div class="collapse" id="detailInfo">
                <div class="card card-body">
                    <h5>{{ blog.get_blog_topic_display }}</h5>
                    <p>{{ blog.description }}</p>
                </div>
              </div>
              <button href="javascript:void();" id="expand" class="expand-more" data-toggle="collapse" data-target="#detailInfo" aria-expanded="false" aria-controls="detailInfo">
                <span id="readmore" class="material-icons">
                    expand_more
                </span>
            </button>
            <div class="posts">
                <h3>Recent posts</h3>
                {% for post in posts %}
                    <div class="card text-center my-4">
                        <div class="card-header text-white" style='background-color: #286da8;'>
                            <!-- {{ post.title }} -->
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ post.title }}</h5>
                            <p class="card-text">{{ post.body|truncatewords:20 }}</p>
                            <a href="#" class="btn btn-primary" style='background-color: #286da8;'>Read</a>
                        </div>
                        <div class="card-footer text-muted">
                            {{ post.create_time }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(".material-icons").on('click', function(){
            $(this).parent().toggleClass("showContent");
            //$('#readmore').text('expand_less');

            var replaceText = $(this).parent().hasClass("showContent") ? "expand_less" : "expand_more"
            $(this).text(replaceText)
        })
    </script>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block title %}
    Blogs
{% endblock %}

{% block content %}
    {% for blog in blogs %}
        <div class="container col-6 my-3">
            <div class="card text-center">
                <div class="card-header text-white" style='background-color: #286da8;'>
                    <a href="#">
                        <div class="link" style='color: white;'>
                            {{ blog.title }}
                         </div>
                    </a>
                </div>
                <div class="card-body">
                <p class="card-title"><strong>{{ blog.get_blog_topic_display }}</strong></>
                <p class="card-text">{{ blog.description }}</p>
                <!-- <a href="#" class="btn btn-primary">Open</a> -->
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/base_blog.css' %}">
    <title>Base</title>

</head>
<body>

    
    <nav class="navbar navbar-expand-lg navbar-dark shadow" style="background-color: #286da8;" id="mainNav">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <span class="material-icons">
                    history_edu
                </span>
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item text-black">
                        <a class="nav-link text-white font-weight-bold" href="#">Posts</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-white font-weight-bold" href="#">Blogs</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-white font-weight-bold" href="#">About</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-white font-weight-bold" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>